version: "3"
services:
  mongo:
      container_name: mongo
      image: mongo
      environment:
        - MONGODB_INITDB_DATABASE=db
      ports:
        - "27017:27017"
  backend:
    container_name: "vincit-2020-backend"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
    depends_on:
      - "mongo"
